@tool
class_name UAGGenerator
extends RefCounted

## Builds the source text of one generated script per [UAGTarget].

const HEADER := "# AUTO-GENERATED BY UID ACCESS GENERATOR - DO NOT EDIT\n# Regenerate via Project > Tools > Generate UAG IDs.\n"


## Returns the full contents of the script for [param target].
static func build_script(target: UAGTarget, entries: Array[UAGScanner.Entry]) -> String:
	var lines := PackedStringArray()

	lines.append(HEADER)
	lines.append("class_name %s" % target.get_class_name())
	lines.append("")
	lines.append("## Generated from [code]%s[/code]%s." % [
		target.get_folder(),
		" (recursive)" if target.recursive else "",
	])
	lines.append("")

	if entries.is_empty():
		lines.append("# No matching files were found in this folder.")
		lines.append("")

	for entry in entries:
		lines.append("const %s := &\"%s\"" % [entry.constant_name, entry.file_name])

	if target.generate_uids:
		lines.append("")
		lines.append_array(_build_uid_block(target, entries))

	if target.generate_enum:
		lines.append("")
		lines.append_array(_build_enum_block(entries))

	if target.generate_enum_names:
		lines.append("")
		lines.append_array(_build_enum_names_block(entries))

	return "\n".join(lines) + "\n"


## Emits a [code]UIDS[/code] dictionary mapping each id to its
## [code]uid://[/code] reference, which is what actually loads the asset:
## the id constants themselves are bare names, not paths.
##
## UIDs survive the file being moved or renamed, unlike a hardcoded path.
static func _build_uid_block(
	target: UAGTarget, entries: Array[UAGScanner.Entry]
) -> PackedStringArray:
	var class_ref := target.get_class_name()
	var mapped := PackedStringArray()

	for entry in entries:
		var uid := entry.get_uid()
		if uid.is_empty():
			push_warning(
				"UAG: '%s' has no UID yet and was left out of UIDS "
				% entry.source_path
				+ "(the editor assigns one on import - rescan and regenerate)."
			)
			continue
		mapped.append("\t%s.%s: &\"%s\"," % [class_ref, entry.constant_name, uid])

	var lines := PackedStringArray()
	lines.append("## Maps each id to its [code]uid://[/code] reference.")
	lines.append("## [codeblock]")
	lines.append("## var res := load(%s.UIDS[%s.SOME_ID])" % [class_ref, class_ref])
	lines.append("## [/codeblock]")

	if mapped.is_empty():
		lines.append("const UIDS: Dictionary[StringName, StringName] = {}")
	else:
		lines.append("const UIDS: Dictionary[StringName, StringName] = {")
		lines.append_array(mapped)
		lines.append("}")

	lines.append("")
	lines.append("## Returns the [code]uid://[/code] for [param id], or [code]&\"\"[/code] if absent.")
	lines.append("static func get_uid_of(id: StringName) -> StringName:")
	lines.append("\treturn UIDS.get(id, &\"\")")

	return lines


## Emits an [code]Id[/code] enum plus a parallel [code]NAMES[/code] array, so a
## property exported as [code]Id[/code] gets a native inspector dropdown and
## resolves back to its [StringName] through [code]get_name_of()[/code].
static func _build_enum_block(entries: Array[UAGScanner.Entry]) -> PackedStringArray:
	var lines := PackedStringArray()

	lines.append("## Inspector-friendly identifiers. Export as")
	lines.append("## [code]@export var id: <ClassName>.Id[/code] for a real dropdown.")

	if entries.is_empty():
		# An empty enum body is a parse error, so keep a placeholder member.
		lines.append("enum Id {")
		lines.append("\tNONE = -1,")
		lines.append("}")
		lines.append("")
		lines.append("## Lookup table aligned with [enum Id].")
		lines.append("const NAMES: Array[StringName] = []")
	else:
		lines.append("enum Id {")
		for index in entries.size():
			lines.append("\t%s = %d," % [entries[index].constant_name, index])
		lines.append("}")
		lines.append("")
		lines.append("## Lookup table aligned with [enum Id].")
		lines.append("const NAMES: Array[StringName] = [")
		for entry in entries:
			lines.append("\t&\"%s\"," % entry.file_name)
		lines.append("]")

	lines.append("")
	lines.append("## Returns the [StringName] for [param id], or [code]&\"\"[/code] if out of range.")
	lines.append("static func get_name_of(id: Id) -> StringName:")
	lines.append("\tvar index := int(id)")
	lines.append("\tif index < 0 or index >= NAMES.size():")
	lines.append("\t\treturn &\"\"")
	lines.append("\treturn NAMES[index]")
	lines.append("")
	lines.append("## Returns the [enum Id] matching [param value], or [code]-1[/code] if absent.")
	lines.append("static func get_id_of(value: StringName) -> int:")
	lines.append("\treturn NAMES.find(value)")

	return lines


## Emits the comma-joined string used with [constant PROPERTY_HINT_ENUM].
## A file name containing a comma would corrupt the hint, so it is excluded
## here while keeping its own constant.
static func _build_enum_names_block(entries: Array[UAGScanner.Entry]) -> PackedStringArray:
	var usable := PackedStringArray()

	for entry in entries:
		if entry.file_name.contains(","):
			push_warning(
				"UAG: '%s' contains a comma and was excluded from ENUM_NAMES "
				% entry.source_path
				+ "(it would corrupt the hint string)."
			)
			continue
		usable.append(entry.file_name)

	var lines := PackedStringArray()
	lines.append("## Comma-joined file names for")
	lines.append("## [code]@export_enum[/code] / [constant PROPERTY_HINT_ENUM] hints.")
	lines.append("const ENUM_NAMES := \"%s\"" % ",".join(usable))
	return lines
